version: "3.8"

services:
  redis:
    image: redis:latest
    command: [
        "redis-server",
        "--appendonly",
        "yes",
        "--port",
        "6379"
      ]
    volumes:
      - redis_data:/data
    networks:
      - rede_geral
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M

  postgres:
    image: postgres:14.13
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: evolution
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rede_geral
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: "0.5"

  evolution_v2:
    image: atendai/evolution-api:v2.1.1-homolog
    volumes:
      - evolution_instancesv2:/evolution/instances
    networks:
      - rede_geral
    ports:
      - "8090:8080"
    depends_on:
      - redis
      - postgres
    environment:
      - SERVER_URL=http://localhost:8090
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_API_KEY=g7hALNaxNgLkBS1MdHpOyV922fhXTZrX
      - AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES=true
      - LANGUAGE=pt-BR
      - DATABASE_CONNECTION_URI=postgresql://postgres:postgres@postgres:5432/evolution
      - CACHE_REDIS_URI=redis://redis:6379/2
      - DATABASE_PROVIDER=postgresql

volumes:
  redis_data:
  postgres_data:
  evolution_instancesv2:

networks:
  rede_geral:
    external: true
