version: '3.7'

services:

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    command: start
    environment:
      - KC_HOSTNAME_PORT=8093
      - KC_HOSTNAME=localhost
      - KC_HOSTNAME_STRICT_BACKCHANNEL=false
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres/${POSTGRES_DB}
      - KC_DB_USERNAME=${POSTGRES_USER}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 8094:8080
    restart: always
    networks:
      - rede_geral


networks:
  rede_geral:
    external: true